### ISSUE TITLE
error: cannot find symbol add(GameServices.class);

### ISSUE THREAD

**Issue by Aprimez** [openforge/capacitor-game-services#23]
How is my MainActivity supposed to look?
I get this error: cannot find symbol add(GameServices.class);
My code looks like this
```
public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        add(GameServices.class);
}
```
What's wrong?

**Comment by Aprimez** [comment]
This is because it doesnt work on Capacitor3

**Comment by crowbait** [comment]
No. Missing symbol most likely comes, because you missed the import statement.
`import io.openforge.gameservices.GameServices;`
For further issues, please open or edit this issue to be more descriptive of the actual problem.
I've had a look at the java source and it should still run. I'm still sure it's possible to use with Cap3.

**Comment by jedihacks** [comment]
@Ricardo385 just updated for v4 - hopefully that helps!

**Comment by KalenGibbons** [comment]
@jedihacks Thank you very much for the update to v4.

However, I'm still seeing the error described in this issue - **cannot find symbol: add(GameServices.class);**

`import android.os.Bundle;
import com.getcapacitor.BridgeActivity;
import io.openforge.gameservices.GameServices;

public class MainActivity extends BridgeActivity {

	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		add(GameServices.class);
	}

}`

Any guidance is appreciated.
